// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with fallback to client-provided credentials
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ofiioxsdxmzncimmshnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9maWlveHNkeG16bmNpbW1zaG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODEyNzAsImV4cCI6MjA3NDY1NzI3MH0.zrYtL_HognblG3sbp063jd0p_A_4g5mKDVKzNQj5mEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});